name: Foodu
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  geocoding: ^3.0.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.8
  url_launcher: ^6.1.10
  jwt_decoder: ^2.0.1
  cupertino_icons: ^1.0.8
  geolocator: ^13.0.1
  smooth_page_indicator: ^1.2.0+3
  get: ^4.6.6
  flutter_launcher_icons: ^0.14.1
  http: ^1.2.2
  flutter_native_splash: ^2.4.1
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  toastification: ^2.3.0
  flutter_advanced_switch: ^3.1.0
  permission_handler: ^11.0.0
dev_dependencies:

  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  remove_alpha_ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 24 # android min sdk min:16, default 21
  adaptive_icon_background: "assets/icons/logo.png" # You can use a color or image for the background
  adaptive_icon_foreground: "assets/icons/logo.png" # For adaptive icons on Android





flutter:
  uses-material-design: true


  assets:
   - assets/images/

  fonts:
    - family: Urbanist-Bold
      fonts:
        - asset: fonts/Urbanist-Bold.ttf
    - family: Urbanist-Regular
      fonts:
          - asset: fonts/Urbanist-Regular.ttf


    - family: Urbanist-SemiBold
      fonts:
        - asset: fonts/Urbanist-SemiBold.ttf

    - family: Lucky-font
      fonts:
        - asset: fonts/LuckiestGuy-Regular.ttf

